version: '3.8'
services:
  pgadmin:
    container_name: "PgADmin"
    image: 'dpage/pgadmin4:latest'
    restart: always
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: zaak0101@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: Zaak1234@
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  postgresql:
    container_name: "PostgreSQL"
    image: 'postgres:12.7'
    restart: always
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: liquidx
      POSTGRES_PASSWORD: Zaak1234
      POSTGRES_DB: coronadb
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
  jupyter:
    container_name: "JupyterLab"
    image: 'jupyter/minimal-notebook'
    restart: always
    ports:
      - "8889:8889"
    environment:
      JUPYTER_ENABLE_LAB: yes
    volumes:
      - notebooks-data:/notebooks
  superset:
    container_name: "Superset"
    image: 'tylerfowler/superset'
    restart: always
    ports:
      - '8088:8088'
      - '5555:5555'
    depends_on:
      - postgresql
    adminUser:
      - username: admin
      - firstname: Abdulrazak
      - lastname: Osman
      - email: zaak0101@hotmail.com
      - password: Zaak1234@
  minio:
    container_image: "MinIO"
    image: 'minio'
    restart: always
    ports:
      - '9000:9000'
    volumes:
      - minio-data:/data
    command:
      - server /data
volumes:
  db-data:
  pgadmin-data:
  minio-data:
  notebooks-data: