version: '3.8'
services:
  pgadmin:
    container_name: "PgADmin"
    image: 'dpage/pgadmin4:latest'
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: zaak0101@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: Zaak1234@
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  postgresql:
    container_name: "PostgreSQL"
    image: 'postgres:12.7'
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: liquidx
      POSTGRES_PASSWORD: Zaak1234
      POSTGRES_DB: coronadb
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
  jupyter:
    container_name: "JupyterLab"
    build: .
    ports:
      - "8888:8888"
    volumes:
      - notebooks:/var/lib/notebooks
volumes:
  db-data:
  notebooks:
  pgadmin-data:
