#The name of the build
name: ETL Pipline Proccess
#Declaring the branches
on:
  push:
    branches:
      - 'main'
  #Setting the time the build will be wunning everyday
  schedule:
    - cron: '0 9 * * *'
jobs:
  build:
    #Here we establishing the os as needed
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    #Setting up python version and action setup
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.10'
    #Installing all needed dependencies
    - name: Installing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    #Running the ETL script to install and update the data as structured
    - name: Running the ETL
      run: |
	./code/python ETL.py
    #Commiting files after updating the dataset
    - name: commit data
      run: |
        git config --local user.email "zaak0101@hotmail.com"
        git config --local user.name "Abdulrazak A. Osman"
        git add -A
        git commit -m "updated data" -a
    #Pushing changes
    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main  
